name: qadaa
description: A new Flutter project.

publish_to: "none"

version: 1.4.0+5

environment:
  # sdk: ">=2.18.5 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: ^0.18.0

dependencies:
  audioplayers: ^1.1.1
  awesome_notifications: ^0.7.4+1
  confetti: ^0.7.0

  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_screen_lock: ^9.0.0+1
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  sleek_circular_slider: ^2.0.1
  url_launcher: ^6.1.7
  wakelock: ^0.6.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#303030"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

flutter_intl:
  enabled: true
