name: qadaa
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^12.0.4
  awesome_notifications: ^0.7.4+1
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  wakelock: ^0.6.2
  flutter_screen_lock: ^9.0.0+1
  get: ^4.6.5
  confetti: ^0.7.0
  audioplayers: ^1.1.1
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#303030"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
