name: qadaa
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^9.2.0
  rxdart: ^0.27.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  wakelock: ^0.6.1+1
  flutter_screen_lock: ^5.0.12
  get: ^4.6.5
  confetti: ^0.6.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
